language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t klin7/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true klin7/docker-react npm run test


