FROM node:alpine

WORKDIR '/app'

COPY package.json .

RUN npm install

COPY . .

## local foler:      Docker Container:
## /frontend         /app
##   /src           <- /reference
##   /public        <- /reference
#    /node_modules  <- /reference


CMD ["npm", "run", "start"]